/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pages;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.db;

/**
 *
 * @author THINKPAD
 */
public class Employee extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    Statement s;

    /**
     * Creates new form Customer
     */
    public Employee() {
        initComponents();
        this.setLocationRelativeTo(null);
        load_table();
        AutoID();
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);

    }

    private void AutoID() {
        try {
            String sql = "SELECT MAX(RIGHT (id,4)) AS id_auto FROM employee";
            Statement s = db.conn().createStatement();
            ResultSet rs = s.executeQuery(sql);

            if (rs.next()) {
                String id_auto, nol_plus;
                int p;
                id_auto = Integer.toString(rs.getInt(1) + 1);
                p = id_auto.length();
                nol_plus = "";
                for (int i = 1; i <= 4 - p; i++) {
                    nol_plus = nol_plus + "0";
                }
                txtID.setText("EMP" + nol_plus + id_auto);
            }
        } catch (Exception e) {
            txtID.setText("EMP0001");

        }
    }

    private void Clear() {
        AutoID();
        cariID.setText("");
        txtNama.setText("");
        txtTelp.setText("");
        txtAlamat.setText("");
        lblID.setVisible(true);
        lblID.setEnabled(true);
        txtID.setVisible(true);
        txtID.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);

    }

    private void load_table() {

        try {

            DefaultTableModel dt = (DefaultTableModel) tblEmployee.getModel();
            dt.setRowCount(0);

            Statement s = db.conn().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM employee");

            while (rs.next()) {

                Vector v = new Vector();

                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));

                dt.addRow(v);

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        sideSales = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sideCustomers = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sideInvoices = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sideSupplier = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sideProduct = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sidePurchase = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sideBill = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sidereturn = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        sideAccount = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        sideEmployee = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cariID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        txtAlamat = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(51, 102, 255));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideSales.setBackground(new java.awt.Color(66, 111, 250));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sales");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/increase.png"))); // NOI18N

        javax.swing.GroupLayout sideSalesLayout = new javax.swing.GroupLayout(sideSales);
        sideSales.setLayout(sideSalesLayout);
        sideSalesLayout.setHorizontalGroup(
            sideSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideSalesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        sideSalesLayout.setVerticalGroup(
            sideSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideSalesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(sideSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebarPanel.add(sideSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 60));

        sideCustomers.setBackground(new java.awt.Color(66, 111, 250));
        sideCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideCustomersMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customers");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customer.png"))); // NOI18N

        javax.swing.GroupLayout sideCustomersLayout = new javax.swing.GroupLayout(sideCustomers);
        sideCustomers.setLayout(sideCustomersLayout);
        sideCustomersLayout.setHorizontalGroup(
            sideCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideCustomersLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        sideCustomersLayout.setVerticalGroup(
            sideCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideCustomersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sideCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22))
        );

        sidebarPanel.add(sideCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 60));

        sideInvoices.setBackground(new java.awt.Color(66, 111, 250));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Invoices");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/invoice.png"))); // NOI18N

        javax.swing.GroupLayout sideInvoicesLayout = new javax.swing.GroupLayout(sideInvoices);
        sideInvoices.setLayout(sideInvoicesLayout);
        sideInvoicesLayout.setHorizontalGroup(
            sideInvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideInvoicesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        sideInvoicesLayout.setVerticalGroup(
            sideInvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideInvoicesLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(sideInvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(22, 22, 22))
        );

        sidebarPanel.add(sideInvoices, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 240, 60));

        sideSupplier.setBackground(new java.awt.Color(66, 111, 250));
        sideSupplier.setPreferredSize(new java.awt.Dimension(240, 60));
        sideSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideSupplierMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Suppliers");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hotel-supplier.png"))); // NOI18N

        javax.swing.GroupLayout sideSupplierLayout = new javax.swing.GroupLayout(sideSupplier);
        sideSupplier.setLayout(sideSupplierLayout);
        sideSupplierLayout.setHorizontalGroup(
            sideSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideSupplierLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        sideSupplierLayout.setVerticalGroup(
            sideSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideSupplierLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(sideSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(22, 22, 22))
        );

        sidebarPanel.add(sideSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 60));

        sideProduct.setBackground(new java.awt.Color(66, 111, 250));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Products");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/package.png"))); // NOI18N

        javax.swing.GroupLayout sideProductLayout = new javax.swing.GroupLayout(sideProduct);
        sideProduct.setLayout(sideProductLayout);
        sideProductLayout.setHorizontalGroup(
            sideProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideProductLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        sideProductLayout.setVerticalGroup(
            sideProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideProductLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sideProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(22, 22, 22))
        );

        sidebarPanel.add(sideProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 240, 60));

        sidePurchase.setBackground(new java.awt.Color(66, 111, 250));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Purchase");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cart.png"))); // NOI18N

        javax.swing.GroupLayout sidePurchaseLayout = new javax.swing.GroupLayout(sidePurchase);
        sidePurchase.setLayout(sidePurchaseLayout);
        sidePurchaseLayout.setHorizontalGroup(
            sidePurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePurchaseLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        sidePurchaseLayout.setVerticalGroup(
            sidePurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePurchaseLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(sidePurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(22, 22, 22))
        );

        sidebarPanel.add(sidePurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 240, 60));

        sideBill.setBackground(new java.awt.Color(66, 111, 250));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PO / Bill");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/invoice (1).png"))); // NOI18N

        javax.swing.GroupLayout sideBillLayout = new javax.swing.GroupLayout(sideBill);
        sideBill.setLayout(sideBillLayout);
        sideBillLayout.setHorizontalGroup(
            sideBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBillLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel14)
                .addGap(40, 40, 40)
                .addComponent(jLabel13)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        sideBillLayout.setVerticalGroup(
            sideBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        sidebarPanel.add(sideBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 240, 60));

        sidereturn.setBackground(new java.awt.Color(66, 111, 250));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Return");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return-box.png"))); // NOI18N

        javax.swing.GroupLayout sidereturnLayout = new javax.swing.GroupLayout(sidereturn);
        sidereturn.setLayout(sidereturnLayout);
        sidereturnLayout.setHorizontalGroup(
            sidereturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidereturnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel16)
                .addGap(36, 36, 36)
                .addComponent(jLabel15)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        sidereturnLayout.setVerticalGroup(
            sidereturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidereturnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sidereturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(26, 26, 26))
        );

        sidebarPanel.add(sidereturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 240, 60));

        sideAccount.setBackground(new java.awt.Color(66, 111, 250));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Account");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bank-building.png"))); // NOI18N

        javax.swing.GroupLayout sideAccountLayout = new javax.swing.GroupLayout(sideAccount);
        sideAccount.setLayout(sideAccountLayout);
        sideAccountLayout.setHorizontalGroup(
            sideAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideAccountLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel18)
                .addGap(34, 34, 34)
                .addComponent(jLabel17)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        sideAccountLayout.setVerticalGroup(
            sideAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        sidebarPanel.add(sideAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 240, 60));

        sideEmployee.setBackground(new java.awt.Color(107, 144, 252));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Employee");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/employment-man.png"))); // NOI18N

        javax.swing.GroupLayout sideEmployeeLayout = new javax.swing.GroupLayout(sideEmployee);
        sideEmployee.setLayout(sideEmployeeLayout);
        sideEmployeeLayout.setHorizontalGroup(
            sideEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideEmployeeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel20)
                .addGap(32, 32, 32)
                .addComponent(jLabel19)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        sideEmployeeLayout.setVerticalGroup(
            sideEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideEmployeeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(sideEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        sidebarPanel.add(sideEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 240, 60));

        jPanel13.setBackground(new java.awt.Color(66, 111, 250));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Report");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report.png"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel22)
                .addGap(32, 32, 32)
                .addComponent(jLabel21)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addGap(26, 26, 26))
        );

        sidebarPanel.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 240, 60));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cashier.png"))); // NOI18N
        sidebarPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 40, 40));

        jLabel24.setFont(new java.awt.Font("Eras Bold ITC", 3, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("POS");
        sidebarPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, -1));

        jPanel1.add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 760));

        headerPanel.setBackground(new java.awt.Color(235, 235, 235));

        txtCari.setToolTipText("");
        txtCari.setMinimumSize(new java.awt.Dimension(8, 20));
        txtCari.setSelectionColor(new java.awt.Color(66, 111, 250));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel31.setText("Search");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(664, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1080, 100));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 157, -1, -1));

        jLabel30.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel30.setText("Employee Info");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel29.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 16)); // NOI18N
        jLabel29.setText("Search ID ");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        cariID.setToolTipText("");
        cariID.setMinimumSize(new java.awt.Dimension(8, 20));
        cariID.setSelectionColor(new java.awt.Color(66, 111, 250));
        cariID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariIDActionPerformed(evt);
            }
        });
        jPanel2.add(cariID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 280, 30));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(66, 111, 250));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magnifying-glass.png"))); // NOI18N
        btnSearch.setMargin(new java.awt.Insets(4, 14, 4, 14));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 40, 30));

        jPanel4.setBackground(new java.awt.Color(242, 242, 242));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel28.setText("Alamat");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setForeground(new java.awt.Color(66, 111, 250));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 120, 30));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(66, 111, 250));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 120, 30));

        jLabel32.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel32.setText("No Telp");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(66, 111, 250));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 120, 30));

        txtAlamat.setToolTipText("");
        txtAlamat.setMinimumSize(new java.awt.Dimension(8, 20));
        txtAlamat.setSelectionColor(new java.awt.Color(66, 111, 250));
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        jPanel4.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 310, 30));

        txtID.setToolTipText("");
        txtID.setMinimumSize(new java.awt.Dimension(8, 20));
        txtID.setSelectionColor(new java.awt.Color(66, 111, 250));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel4.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 310, 30));

        txtTelp.setToolTipText("");
        txtTelp.setMinimumSize(new java.awt.Dimension(8, 20));
        txtTelp.setSelectionColor(new java.awt.Color(66, 111, 250));
        txtTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelpActionPerformed(evt);
            }
        });
        jPanel4.add(txtTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 310, 30));

        jLabel33.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel33.setText("Nama");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        txtNama.setToolTipText("");
        txtNama.setMinimumSize(new java.awt.Dimension(8, 20));
        txtNama.setSelectionColor(new java.awt.Color(66, 111, 250));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel4.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 310, 30));

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(66, 111, 250));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        btnRefresh.setMargin(new java.awt.Insets(4, 14, 4, 14));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel4.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 40, 30));

        lblID.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblID.setText("Employee ID");
        jPanel4.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        tblEmployee.setBackground(new java.awt.Color(242, 242, 242));
        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "No Telp", "Alamat"
            }
        ));
        tblEmployee.setGridColor(new java.awt.Color(66, 111, 250));
        tblEmployee.setSelectionBackground(new java.awt.Color(66, 111, 250));
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEmployee);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel1.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 1080, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        Clear();

    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
        String nama = txtNama.getText();
        String telp = txtTelp.getText();
        String alamat = txtAlamat.getText();

        if (txtNama.getText().equals("") || txtTelp.getText().equals("") || txtAlamat.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Data tidak boleh kosong");
        } else {

            try {
                Statement s = db.conn().createStatement();
                s.executeUpdate(" INSERT INTO employee (id,nama, telp, alamat) VALUES (' " + id + "',  ' " + nama + " ', ' " + telp + " ', ' " + alamat + " ') ");
                AutoID();
                Clear();
                JOptionPane.showMessageDialog(rootPane, "Berhasil Menambah data");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
            load_table();
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String nama = txtNama.getText();
        String telp = txtTelp.getText();
        String alamat = txtAlamat.getText();
        String id = cariID.getText();

        try {
            Statement s = db.conn().createStatement();
            s.executeUpdate("UPDATE employee SET nama = '" + nama + "', telp = '" + telp + "', alamat = '" + alamat + "' WHERE id = '" + id + "' ");
            AutoID();
            Clear();
            JOptionPane.showMessageDialog(rootPane, "Berhasil Mengupdate data");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);

        }
        load_table();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String id = cariID.getText();

        try {
            Statement s = db.conn().createStatement();
            s.executeUpdate("DELETE FROM employee WHERE id = ' " + id + " ' ");
            JOptionPane.showMessageDialog(rootPane, "Berhasil menghapus data");
            AutoID();
            Clear();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        load_table();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void cariIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariIDActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
        // TODO add your handling code here:
        int r = tblEmployee.getSelectedRow();

        String id = tblEmployee.getValueAt(r, 0).toString();
        String nama = tblEmployee.getValueAt(r, 1).toString();
        String telp = tblEmployee.getValueAt(r, 2).toString();
        String alamat = tblEmployee.getValueAt(r, 3).toString();

        cariID.setText(id);
        txtNama.setText(nama);
        txtTelp.setText(telp);
        txtAlamat.setText(alamat);

        lblID.setVisible(false);
        lblID.setEnabled(false);
        txtID.setVisible(false);
        txtID.setEnabled(false);

        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);


    }//GEN-LAST:event_tblEmployeeMouseClicked

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String search = cariID.getText();

        try {
            Statement s = db.conn().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM employee WHERE id = ' " + search + " ' ");

            if (rs.next()) {
                txtID.setText(rs.getString("id"));
                txtNama.setText(rs.getString("nama"));
                txtTelp.setText(rs.getString("telp"));
                txtAlamat.setText(rs.getString("alamat"));
                btnSave.setEnabled(false);
                btnUpdate.setEnabled(true);
                btnDelete.setEnabled(true);

            } else {
                JOptionPane.showMessageDialog(rootPane, "Tidak menemukan data dengan Employee ID " + cariID.getText());
                btnSave.setEnabled(true);
                btnUpdate.setEnabled(false);
                btnDelete.setEnabled(false);
                Clear();

            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        String nama = txtCari.getText();

        try {
            DefaultTableModel dt = (DefaultTableModel) tblEmployee.getModel();
            dt.setRowCount(0);
            Statement s = db.conn().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM employee WHERE nama = ' " + nama + " ' ");

            while (rs.next()) {
                Vector v = new Vector();

                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));

                dt.addRow(v);

            }
        } catch (Exception e) {
            load_table();
        }
    }//GEN-LAST:event_txtCariKeyReleased

    private void sideCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideCustomersMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Customer c = new Customer();
        c.setVisible(true);
    }//GEN-LAST:event_sideCustomersMouseClicked

    private void sideSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideSupplierMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Supplier s = new Supplier();
        s.setVisible(true);
    }//GEN-LAST:event_sideSupplierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField cariID;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblID;
    private javax.swing.JPanel sideAccount;
    private javax.swing.JPanel sideBill;
    private javax.swing.JPanel sideCustomers;
    private javax.swing.JPanel sideEmployee;
    private javax.swing.JPanel sideInvoices;
    private javax.swing.JPanel sideProduct;
    private javax.swing.JPanel sidePurchase;
    private javax.swing.JPanel sideSales;
    private javax.swing.JPanel sideSupplier;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel sidereturn;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables
}
