/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pages;

import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import koneksi.db;

/**
 *
 * @author THINKPAD
 */
public class Sale extends javax.swing.JFrame {

    /**
     * Creates new form Sale
     */
    public Sale() {
        initComponents();
        data_load();
    }

    private void data_load() {

        try {
            Statement s = db.conn().createStatement();

            ResultSet rs = s.executeQuery("SELECT * FROM customer ");
            Vector v = new Vector();

            while (rs.next()) {
                v.add(rs.getString("nama"));

                DefaultComboBoxModel com = new DefaultComboBoxModel(v);
                comboCustomer.setModel(com);
            }

        } catch (Exception e) {
            System.out.println(e);
        }

        try {
            Statement s = db.conn().createStatement();

            ResultSet rs = s.executeQuery("SELECT * FROM product ");
            Vector v = new Vector();

            while (rs.next()) {
                v.add(rs.getString("nama"));

                DefaultComboBoxModel com = new DefaultComboBoxModel(v);
                comboProduct.setModel(com);
            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        sideSales = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sideCustomers = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sideInvoices = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sideSupplier = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sideProduct = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sidePurchase = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sideBill = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sidereturn = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        sideAccount = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        sideEmployee = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblInvoice = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        comboCustomer = new javax.swing.JComboBox<>();
        comboProduct = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSale = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        txtHarga = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jmlhTotal = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        jmlhBayar = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btnAllHapus = new javax.swing.JButton();
        keranjang = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(51, 102, 255));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideSales.setBackground(new java.awt.Color(107, 144, 252));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sales");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/increase.png"))); // NOI18N

        javax.swing.GroupLayout sideSalesLayout = new javax.swing.GroupLayout(sideSales);
        sideSales.setLayout(sideSalesLayout);
        sideSalesLayout.setHorizontalGroup(
            sideSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideSalesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        sideSalesLayout.setVerticalGroup(
            sideSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideSalesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(sideSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebarPanel.add(sideSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 60));

        sideCustomers.setBackground(new java.awt.Color(66, 111, 250));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customers");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customer.png"))); // NOI18N

        javax.swing.GroupLayout sideCustomersLayout = new javax.swing.GroupLayout(sideCustomers);
        sideCustomers.setLayout(sideCustomersLayout);
        sideCustomersLayout.setHorizontalGroup(
            sideCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideCustomersLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        sideCustomersLayout.setVerticalGroup(
            sideCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideCustomersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sideCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22))
        );

        sidebarPanel.add(sideCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 60));

        sideInvoices.setBackground(new java.awt.Color(66, 111, 250));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Invoices");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/invoice.png"))); // NOI18N

        javax.swing.GroupLayout sideInvoicesLayout = new javax.swing.GroupLayout(sideInvoices);
        sideInvoices.setLayout(sideInvoicesLayout);
        sideInvoicesLayout.setHorizontalGroup(
            sideInvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideInvoicesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        sideInvoicesLayout.setVerticalGroup(
            sideInvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideInvoicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sideInvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(487, 487, 487))
        );

        sidebarPanel.add(sideInvoices, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 240, 60));

        sideSupplier.setBackground(new java.awt.Color(66, 111, 250));
        sideSupplier.setPreferredSize(new java.awt.Dimension(240, 60));
        sideSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideSupplierMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Suppliers");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hotel-supplier.png"))); // NOI18N

        javax.swing.GroupLayout sideSupplierLayout = new javax.swing.GroupLayout(sideSupplier);
        sideSupplier.setLayout(sideSupplierLayout);
        sideSupplierLayout.setHorizontalGroup(
            sideSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideSupplierLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        sideSupplierLayout.setVerticalGroup(
            sideSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideSupplierLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(sideSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(22, 22, 22))
        );

        sidebarPanel.add(sideSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 60));

        sideProduct.setBackground(new java.awt.Color(66, 111, 250));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Products");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/package.png"))); // NOI18N

        javax.swing.GroupLayout sideProductLayout = new javax.swing.GroupLayout(sideProduct);
        sideProduct.setLayout(sideProductLayout);
        sideProductLayout.setHorizontalGroup(
            sideProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideProductLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        sideProductLayout.setVerticalGroup(
            sideProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideProductLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sideProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(22, 22, 22))
        );

        sidebarPanel.add(sideProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 240, 60));

        sidePurchase.setBackground(new java.awt.Color(66, 111, 250));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Purchase");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cart.png"))); // NOI18N

        javax.swing.GroupLayout sidePurchaseLayout = new javax.swing.GroupLayout(sidePurchase);
        sidePurchase.setLayout(sidePurchaseLayout);
        sidePurchaseLayout.setHorizontalGroup(
            sidePurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePurchaseLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        sidePurchaseLayout.setVerticalGroup(
            sidePurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePurchaseLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(sidePurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(22, 22, 22))
        );

        sidebarPanel.add(sidePurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 240, 60));

        sideBill.setBackground(new java.awt.Color(66, 111, 250));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PO / Bill");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/invoice (1).png"))); // NOI18N

        javax.swing.GroupLayout sideBillLayout = new javax.swing.GroupLayout(sideBill);
        sideBill.setLayout(sideBillLayout);
        sideBillLayout.setHorizontalGroup(
            sideBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBillLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel14)
                .addGap(40, 40, 40)
                .addComponent(jLabel13)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        sideBillLayout.setVerticalGroup(
            sideBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        sidebarPanel.add(sideBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 240, 60));

        sidereturn.setBackground(new java.awt.Color(66, 111, 250));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Return");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return-box.png"))); // NOI18N

        javax.swing.GroupLayout sidereturnLayout = new javax.swing.GroupLayout(sidereturn);
        sidereturn.setLayout(sidereturnLayout);
        sidereturnLayout.setHorizontalGroup(
            sidereturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidereturnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel16)
                .addGap(36, 36, 36)
                .addComponent(jLabel15)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        sidereturnLayout.setVerticalGroup(
            sidereturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidereturnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sidereturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(26, 26, 26))
        );

        sidebarPanel.add(sidereturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 240, 60));

        sideAccount.setBackground(new java.awt.Color(66, 111, 250));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Account");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bank-building.png"))); // NOI18N

        javax.swing.GroupLayout sideAccountLayout = new javax.swing.GroupLayout(sideAccount);
        sideAccount.setLayout(sideAccountLayout);
        sideAccountLayout.setHorizontalGroup(
            sideAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideAccountLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel18)
                .addGap(34, 34, 34)
                .addComponent(jLabel17)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        sideAccountLayout.setVerticalGroup(
            sideAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        sidebarPanel.add(sideAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 240, 60));

        sideEmployee.setBackground(new java.awt.Color(66, 111, 250));
        sideEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideEmployeeMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Employee");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/employment-man.png"))); // NOI18N

        javax.swing.GroupLayout sideEmployeeLayout = new javax.swing.GroupLayout(sideEmployee);
        sideEmployee.setLayout(sideEmployeeLayout);
        sideEmployeeLayout.setHorizontalGroup(
            sideEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideEmployeeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel20)
                .addGap(35, 35, 35)
                .addComponent(jLabel19)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        sideEmployeeLayout.setVerticalGroup(
            sideEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        sidebarPanel.add(sideEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 240, 60));

        jPanel13.setBackground(new java.awt.Color(66, 111, 250));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Report");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report.png"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel22)
                .addGap(32, 32, 32)
                .addComponent(jLabel21)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addGap(26, 26, 26))
        );

        sidebarPanel.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 240, 60));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cashier.png"))); // NOI18N
        sidebarPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 40, 40));

        jLabel24.setFont(new java.awt.Font("Eras Bold ITC", 3, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("POS");
        sidebarPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, -1));

        jPanel1.add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 820));

        headerPanel.setBackground(new java.awt.Color(235, 235, 235));

        txtCari.setToolTipText("");
        txtCari.setMinimumSize(new java.awt.Dimension(8, 20));
        txtCari.setSelectionColor(new java.awt.Color(66, 111, 250));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel31.setText("Search");

        jLabel30.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel30.setText("Invoice No : ");

        lblInvoice.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        lblInvoice.setText("0");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInvoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 633, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(29, 29, 29)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30)
                    .addComponent(lblInvoice))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1190, 100));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 157, -1, -1));

        lblHarga.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        lblHarga.setText("0");
        jPanel2.add(lblHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, -1, -1));

        jLabel39.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel39.setText("Product :");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel40.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel40.setText("Qty :");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        comboCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Customer" }));
        comboCustomer.setToolTipText("");
        comboCustomer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        comboCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCustomerActionPerformed(evt);
            }
        });
        jPanel2.add(comboCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 170, 30));

        comboProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Product" }));
        comboProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductActionPerformed(evt);
            }
        });
        jPanel2.add(comboProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 170, 30));

        jLabel41.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel41.setText("Harga :");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, -1, -1));

        jLabel43.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel43.setText("Customer :");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtQty.setToolTipText("");
        txtQty.setMinimumSize(new java.awt.Dimension(8, 20));
        txtQty.setSelectionColor(new java.awt.Color(66, 111, 250));
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        jPanel2.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 90, 30));

        contentPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, 1160, 80));

        jPanel4.setBackground(new java.awt.Color(242, 242, 242));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Bar Code", "Qty", "Harga", "Total Harga"
            }
        ));
        jScrollPane1.setViewportView(tblSale);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 900, 330));

        contentPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 124, 920, 354));

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(66, 111, 250));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        btnRefresh.setMargin(new java.awt.Insets(4, 14, 4, 14));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        contentPanel.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 40, 30));

        txtHarga.setToolTipText("");
        txtHarga.setMinimumSize(new java.awt.Dimension(8, 20));
        txtHarga.setSelectionColor(new java.awt.Color(66, 111, 250));
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        contentPanel.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 310, 30));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(66, 111, 250));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        contentPanel.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 120, 30));

        jLabel28.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel28.setText("Supplier");
        contentPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel42.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel42.setText("Jumlah Pembayaran : ");

        jPanel5.setBackground(new java.awt.Color(66, 111, 250));

        jLabel44.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Jumlah Total :");

        jmlhTotal.setToolTipText("");
        jmlhTotal.setMinimumSize(new java.awt.Dimension(8, 20));
        jmlhTotal.setSelectionColor(new java.awt.Color(66, 111, 250));
        jmlhTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlhTotalActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Kembalian     :");

        txtKembalian.setToolTipText("");
        txtKembalian.setMinimumSize(new java.awt.Dimension(8, 20));
        txtKembalian.setSelectionColor(new java.awt.Color(66, 111, 250));
        txtKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKembalianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel45)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jmlhTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmlhTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jmlhBayar.setToolTipText("");
        jmlhBayar.setMinimumSize(new java.awt.Dimension(8, 20));
        jmlhBayar.setSelectionColor(new java.awt.Color(66, 111, 250));
        jmlhBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlhBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addGap(18, 18, 18)
                .addComponent(jmlhBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel42)
                        .addComponent(jmlhBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        contentPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 490, 920, 160));

        jPanel8.setBackground(new java.awt.Color(242, 242, 242));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAllHapus.setBackground(new java.awt.Color(255, 255, 255));
        btnAllHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAllHapus.setForeground(new java.awt.Color(66, 111, 250));
        btnAllHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnAllHapus.setText("  Hapus Semua");
        btnAllHapus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAllHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllHapusActionPerformed(evt);
            }
        });
        jPanel8.add(btnAllHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 40));

        keranjang.setBackground(new java.awt.Color(255, 255, 255));
        keranjang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        keranjang.setForeground(new java.awt.Color(66, 111, 250));
        keranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cart (1).png"))); // NOI18N
        keranjang.setText("  Tambah Keranjang");
        keranjang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        keranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keranjangActionPerformed(evt);
            }
        });
        jPanel8.add(keranjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 40));

        btnHapus.setBackground(new java.awt.Color(255, 255, 255));
        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(66, 111, 250));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete (1).png"))); // NOI18N
        btnHapus.setText("  Hapus");
        btnHapus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel8.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, 40));

        contentPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 124, 214, 530));

        btnBayar.setBackground(new java.awt.Color(66, 111, 250));
        btnBayar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBayar.setForeground(new java.awt.Color(255, 255, 255));
        btnBayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/invoice.png"))); // NOI18N
        btnBayar.setText("  Bayar & Print");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
        contentPanel.add(btnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 670, 180, 40));

        jPanel1.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 1180, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sideSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideSupplierMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Supplier s = new Supplier();
        s.setVisible(true);
    }//GEN-LAST:event_sideSupplierMouseClicked

    private void sideEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideEmployeeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Employee e = new Employee();
        e.setVisible(true);
    }//GEN-LAST:event_sideEmployeeMouseClicked

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCariKeyReleased

    private void comboCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCustomerActionPerformed

    private void comboProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductActionPerformed
        // TODO add your handling code here:
        String namaProduct = comboProduct.getSelectedItem().toString();
        try {

            Statement s = db.conn().createStatement();
            ResultSet rs = s.executeQuery("SELECT (harga) FROM product WHERE nama = ' " + namaProduct + " '  ");
            
            if (rs.next()) {
                lblHarga.setText(rs.getString("harga"));
                JOptionPane.showMessageDialog(null, "Berhasil");

            }
            JOptionPane.showMessageDialog(null, "Gagal");

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_comboProductActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAllHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllHapusActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAllHapusActionPerformed

    private void keranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keranjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keranjangActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBayarActionPerformed

    private void jmlhTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlhTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlhTotalActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void jmlhBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlhBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlhBayarActionPerformed

    private void txtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllHapus;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> comboCustomer;
    private javax.swing.JComboBox<String> comboProduct;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlhBayar;
    private javax.swing.JTextField jmlhTotal;
    private javax.swing.JButton keranjang;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblInvoice;
    private javax.swing.JPanel sideAccount;
    private javax.swing.JPanel sideBill;
    private javax.swing.JPanel sideCustomers;
    private javax.swing.JPanel sideEmployee;
    private javax.swing.JPanel sideInvoices;
    private javax.swing.JPanel sideProduct;
    private javax.swing.JPanel sidePurchase;
    private javax.swing.JPanel sideSales;
    private javax.swing.JPanel sideSupplier;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel sidereturn;
    private javax.swing.JTable tblSale;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
}
